# Generated by Django 5.2.6 on 2025-09-19 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('cohorte', models.CharField(max_length=20)),
                ('modalidad', models.CharField(max_length=50)),
                ('iEstado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iEstado', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planes_pago.planpago')),
            ],
        ),
    ]
