# Generated by Django 5.2.6 on 2025-10-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_pago', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpago',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('S', 'Suspendido'), ('D', 'Desactivado')], default='A', max_length=1),
        ),
    ]
