# Generated by Django 5.2.5 on 2025-10-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_pago', '0002_planpago_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpago',
            name='cohorte',
            field=models.CharField(max_length=10),
        ),
    ]
