# Generated by Django 5.2.5 on 2025-11-13 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_pago', '0003_alter_planpago_cohorte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regularizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('carrera', models.CharField(choices=[('INICIAL', 'Meestra nivel inicial'), ('ASI', 'Analisis de Sistemas'), ('INGLES', 'Profesorado de Ingles'), ('Psic', 'Psicopedagogia')], default='ASI', max_length=20, verbose_name='Carrera Seleccionada')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual'), ('MIXTA', 'Mixta')], default='PRESENCIAL', max_length=20, verbose_name='Modalidad de Cursada')),
                ('cohorte', models.CharField(max_length=15)),
                ('estado', models.CharField(choices=[('A', 'Activa'), ('S', 'Suspendida'), ('D', 'Desactivada')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReglaMora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_recargo', models.CharField(blank=True, choices=[('PORCENTUAL', 'Un porcentaje  respecto a la cuota vencida'), ('FIJO', 'Monto Fijo de Multa')], max_length=10, null=True, verbose_name='Tipo de Recargo')),
                ('cantidad_recargo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Tasa/Monto de Recargo')),
                ('frecuencia_aplicacion', models.CharField(blank=True, choices=[('UNA_VEZ', 'Una Sola Vez'), ('QUINCENAL', 'Cada 15 días'), ('DIARIA', 'Diaria')], max_length=10, null=True, verbose_name='Frecuencia de aplicación')),
                ('veces_aplicacion', models.IntegerField(default=0, help_text='Veces que se aplicará el recargo según la frecuencia seleccionada', verbose_name='Veces de Aplicación')),
                ('dias_gracia', models.IntegerField(default=3, help_text='Cantidad de días antes de que se aplique recargo post vencimiento', verbose_name='Días de Gracia')),
                ('regularizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_mora', to='planes_pago.regularizacion', verbose_name='Regularización asociada')),
            ],
        ),
        migrations.CreateModel(
            name='ReglaEstructura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen_deuda', models.CharField(choices=[('FIJO', 'Monto Fijo'), ('TOTAL', 'Total de Deuda')], max_length=10)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tasa', models.DecimalField(decimal_places=2, help_text='Tasa en porcentaje (ej. 10.5)', max_digits=5)),
                ('pago_incial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_de_cuotas', models.IntegerField(default=1)),
                ('frecuencia_de_pago', models.CharField(choices=[('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral')], max_length=10)),
                ('dia_vencimiento', models.IntegerField(default=1, help_text='Día del mes (1 al 31) en que vencerá la cuota.', verbose_name='Día de Vencimiento')),
                ('regularizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_estructura', to='planes_pago.regularizacion', verbose_name='Regularización asociada')),
            ],
        ),
    ]
