# Generated by Django 5.2.6 on 2025-11-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_pago', '0004_regularizacion_reglamora_reglaestructura'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularizacion',
            name='iEstado',
            field=models.BooleanField(default=True),
        ),
    ]
