# Generated by Django 5.2.6 on 2025-11-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_pago', '0005_regularizacion_iestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularizacion',
            name='iEstado',
        ),
        migrations.AddField(
            model_name='regularizacion',
            name='tipo',
            field=models.CharField(default='Regularización', max_length=20),
        ),
    ]
