# Generated by Django 5.2.6 on 2025-11-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_pago', '0006_remove_regularizacion_iestado_regularizacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planpago',
            name='tipo',
            field=models.CharField(default='Plan normal', max_length=20),
        ),
    ]
