# Generated by Django 5.2.6 on 2025-11-17 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_pago', '0007_planpago_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaRegularizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField(verbose_name='Número de Cuota')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la Cuota')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('PA', 'Pagada'), ('V', 'Vencida')], default='P', max_length=2, verbose_name='Estado')),
                ('regularizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='planes_pago.regularizacion', verbose_name='Regularización asociada')),
            ],
            options={
                'verbose_name': 'Cuota de Regularización',
                'verbose_name_plural': 'Cuotas de Regularización',
                'ordering': ['numero_cuota'],
            },
        ),
    ]
