# Generated by Django 5.2.6 on 2025-11-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes_pago', '0008_cuotaregularizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaregularizacion',
            name='monto_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Base'),
        ),
        migrations.AddField(
            model_name='cuotaregularizacion',
            name='monto_interes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Interés'),
        ),
        migrations.AddField(
            model_name='cuotaregularizacion',
            name='monto_mora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Recargo por Mora'),
        ),
    ]
